---
name: CI

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pdm install
      - name: Lint
        run: |
          pdm run lint
      - name: Test
        run: |
          pdm run test

